apiVersion: batch/v1
kind: Job
metadata:
  name: serverpod-migration-job-todo
  namespace: todo-app
spec:
  template:
    spec:
      imagePullSecrets:
        - name: timeweb-registry-secret
      containers:
        - name: migrator-todo
          image: ...registry.twcstorage.ru/todo-server:latest
          command:
            [
              "/usr/local/bin/server",
              "--apply-migrations",
              "--mode",
              "production",
              "--role",
              "maintenance",
            ]

          envFrom:
            - configMapRef:
                name: serverpod-config-todo
          env:
            - name: SERVERPOD_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: serverpod-secrets-todo
                  key: database-password
            - name: SERVERPOD_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: serverpod-secrets-todo
                  key: redis-password
            - name: SERVERPOD_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: serverpod-secrets-todo
                  key: service-secret
      restartPolicy: Never
  backoffLimit: 2
